### ISSUE TITLE
Release is missing a required update file for current platform

### ISSUE THREAD

**Issue by OldManMeta** [christianblandford/electron-github-autoupdater#3]
The error I am seeing is the following"

`[2023-04-08 13:44:33.919] [error] Error checking for update: Error: Release is missing a required update file for current platform (win32)
    at C:\Users\mrbre\source\repos\COSMOS\cosmos-builder\node_modules\electron-github-autoupdater\dist\autoUpdater.js:294:39
    at Array.map (<anonymous>)
    at ElectronGithubAutoUpdater.<anonymous> (C:\Users\mrbre\source\repos\COSMOS\cosmos-builder\node_modules\electron-github-autoupdater\dist\autoUpdater.js:291:68)
    at step (C:\Users\mrbre\source\repos\COSMOS\cosmos-builder\node_modules\electron-github-autoupdater\dist\autoUpdater.js:59:23)
    at Object.next (C:\Users\mrbre\source\repos\COSMOS\cosmos-builder\node_modules\electron-github-autoupdater\dist\autoUpdater.js:40:53)
    at C:\Users\mrbre\source\repos\COSMOS\cosmos-builder\node_modules\electron-github-autoupdater\dist\autoUpdater.js:34:71
    at new Promise (<anonymous>)
    at __awaiter (C:\Users\mrbre\source\repos\COSMOS\cosmos-builder\node_modules\electron-github-autoupdater\dist\autoUpdater.js:30:12)
    at ElectronGithubAutoUpdater._this.downloadUpdateFromRelease (C:\Users\mrbre\source\repos\COSMOS\cosmos-builder\node_modules\electron-github-autoupdater\dist\autoUpdater.js:283:71)
    at ElectronGithubAutoUpdater.<anonymous> (C:\Users\mrbre\source\repos\COSMOS\cosmos-builder\node_modules\electron-github-autoupdater\dist\autoUpdater.js:437:51)`

Looking through the source code, at line 188 in autoUpdater.js we have this :
```
requiredFiles: [/[^ ]*-full\.nupkg/gim, /RELEASES/],
```

Considering that my release is being auto-packaged and released by electron-builder, I am unsure what exactly is missing as the error is not very helpful.

What is the filename supposed to be, or what file is it looking for?

Cheers

**Comment by rugobal** [comment]
Hi, have you found the solution for this error? I'm having the same problem

**Comment by linus-aegu** [comment]
do you have a file ending with the `.nupkg` extension in your release?

**Comment by linus-aegu** [comment]
> The error I am seeing is the following"
> 
> `[2023-04-08 13:44:33.919] [error] Error checking for update: Error: Release is missing a required update file for current platform (win32) at C:\Users\mrbre\source\repos\COSMOS\cosmos-builder\node_modules\electron-github-autoupdater\dist\autoUpdater.js:294:39 at Array.map (<anonymous>) at ElectronGithubAutoUpdater.<anonymous> (C:\Users\mrbre\source\repos\COSMOS\cosmos-builder\node_modules\electron-github-autoupdater\dist\autoUpdater.js:291:68) at step (C:\Users\mrbre\source\repos\COSMOS\cosmos-builder\node_modules\electron-github-autoupdater\dist\autoUpdater.js:59:23) at Object.next (C:\Users\mrbre\source\repos\COSMOS\cosmos-builder\node_modules\electron-github-autoupdater\dist\autoUpdater.js:40:53) at C:\Users\mrbre\source\repos\COSMOS\cosmos-builder\node_modules\electron-github-autoupdater\dist\autoUpdater.js:34:71 at new Promise (<anonymous>) at __awaiter (C:\Users\mrbre\source\repos\COSMOS\cosmos-builder\node_modules\electron-github-autoupdater\dist\autoUpdater.js:30:12) at ElectronGithubAutoUpdater._this.downloadUpdateFromRelease (C:\Users\mrbre\source\repos\COSMOS\cosmos-builder\node_modules\electron-github-autoupdater\dist\autoUpdater.js:283:71) at ElectronGithubAutoUpdater.<anonymous> (C:\Users\mrbre\source\repos\COSMOS\cosmos-builder\node_modules\electron-github-autoupdater\dist\autoUpdater.js:437:51)`
> 
> Looking through the source code, at line 188 in autoUpdater.js we have this :
> 
> ```
> requiredFiles: [/[^ ]*-full\.nupkg/gim, /RELEASES/],
> ```
> 
> Considering that my release is being auto-packaged and released by electron-builder, I am unsure what exactly is missing as the error is not very helpful.
> 
> What is the filename supposed to be, or what file is it looking for?
> 
> Cheers

do you have a file ending with the `.nupkg` extension in your release?


My release assets look like this and I just figured it could be the file you are missing?

<img width="947" alt="Image" src="https://github.com/user-attachments/assets/20791269-716d-47a5-bdd0-fd95d2f6da68" />
